-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 19:12:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vanguard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vanguard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vanguard` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `vanguard` ;

-- -----------------------------------------------------
-- Table `vanguard`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanguard`.`Usuario` (
  `senha` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL,
  `telefone` CHAR(10) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
